name: tom_vscode_bridge
description: D4rt bridge server for VS Code extension integration.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  tom_vscode_scripting_api:
  tom_d4rt:
  tom_dartscript_bridges:
    path: ../../../dartscript/tom_dartscript_bridges

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.4
  build: ^4.0.3

dependency_overrides:
  runtime_native_semaphores:
    git:
      url: https://github.com/al-the-bear/native_semaphores.git
      ref: fork-fix

